version: "3.8"
services:
  server:
    build: ./server
    container_name: pets_server
    ports:
      - "8000:8000"

  client:
    build: ./client
    container_name: pets_client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
