const accessoryDetails = [
  {
    productType: "Accessory",
    petType: "dog",
    name: "Bow Tie",
    price: 1999,
    src: "./../img/images/ac1.avif",
  },
  {
    productType: "Accessory",
    petType: "dog",
    name: "Dog non-slip Socks",
    price: 199,
    src: "./../img/images/ac17.jpg",
  },
  {
    productType: "Accessory",
    petType: "cat",
    name: "Cat scratching Ball Toy",
    price: 1999,
    src: "./../img/images/ac19.jpg",
  },
  {
    productType: "Accessory",
    petType: "dog",
    name: "Pawstop Dog Belt",
    price: 1499,
    src: "./../img/images/ac2.jpg",
  },
  {
    productType: "Accessory",
    petType: "cat",
    name: "Buraq Cat Harness Full Body with Leash Set - for Walking",
    price: 199,
    src: "./../img/images/ac3.jpg",
  },
  {
    productType: "Accessory",
    petType: "cat",
    name: "Jingle Bell for Cat Collar",
    price: 500,
    src: "./../img/images/ac4.jpg",
  },
  {
    productType: "Accessory",
    petType: "bird",
    name: "Bath Box Bird Cage",
    price: 250,
    src: "./../img/images/ac5.jpg",
  },
  {
    productType: "Accessory",
    petType: "bird",
    name: "Bird Parrot Feeder Cage Fruit Vegetable Holder",
    price: 150,
    src: "./../img/images/ac6.jpg",
  },
  {
    productType: "Accessory",
    petType: "fish",
    name: "Aquarium",
    price: 1050,
    src: "./../img/images/ac7.jpg",
  },
  {
    productType: "Accessory",
    petType: "fish",
    name: "mall Fish Hideout Betta Cave Aquarium Decorations",
    price: 300,
    src: "./../img/images/ac8.jpg",
  },
  {
    productType: "Accessory",
    petType: "dog",
    name: "Glitter Gold Bone Dog name ID Tag",
    price: 1999,
    src: "./../img/images/ac9.jpg",
  },
  {
    productType: "Accessory",
    petType: "dog",
    name: "Personalized Dog Bone Pet Charm",
    price: 425,
    src: "./../img/images/ac18.jpg",
  },
  {
    productType: "Accessory",
    petType: "fish",
    name: "Hunar Quick Fish Catching Nets with Long Handle Aquarium Accessory for Fish Tank Water Tank(Set of 2)",
    price: 350,
    src: "./../img/images/ac20.jpg",
  },
  {
    productType: "Accessory",
    petType: "bird",
    name: "NATLIS Bird Cage, House for Parrot, Rabbit and Small Pets",
    price: 900,
    src: "./../img/images/ac10.jpg",
  },
  {
    productType: "Accessory",
    petType: "cat",
    name: "Soft Plush Donut Cuddler Cushion",
    price: 2149,
    src: "./../img/images/ac11.jpg",
  },
  {
    productType: "Accessory",
    petType: "cat",
    name: "Cute and Funny Pet Sunglasses",
    price: 1499,
    src: "./../img/images/ac12.avif",
  },
  {
    productType: "Accessory",
    petType: "bird",
    name: "Bird Perch Bird Stand Platform Toy",
    price: 2623,
    src: "./../img/images/ac13.jpg",
  },
  {
    productType: "Accessory",
    petType: "bird",
    name: "Hanging Ring Plastic Swing Toy (Pack of 3)",
    price: 169,
    src: "./../img/images/ac14.jpg",
  },
  {
    productType: "Accessory",
    petType: "fish",
    name: "Colourful - High Glass Submersible Automatic On/Off",
    price: 1299,
    src: "./../img/images/ac15.jpg",
  },
  {
    productType: "Accessory",
    petType: "fish",
    name: "Decorative Ornaments for Fish Tank Decoration",
    price: 659,
    src: "./../img/images/ac16.jpg",
  },
];

export default accessoryDetails;
