import express from "express";
import Product from "../../server/models/Product.js";
const router = express.Router();

const foodDetails = [
  {
    productType: "food",
    petType: "dog",
    name: "Pedigree for adult dog",
    price: 449,
    src: "../../img/foodservicesLandingPage/dogFood1.jpg",
  },
  {
    productType: "food",
    petType: "fish",
    name: "Omega One pellets for fish",
    price: 349,
    src: "../../img/foodservicesLandingPage/fishFood1.jpg",
  },
  {
    productType: "food",
    petType: "cat",
    name: "Whiskas food for cats",
    price: 649,
    src: "../../img/foodservicesLandingPage/catFood1.jpg",
  },
  {
    productType: "food",
    petType: "bird",
    name: "IuPreem food for parrots",
    price: 349,
    src: "./../img/foodservicesLandingPage/birdFood1.jpg",
  },
  {
    productType: "food",
    petType: "dog",
    name: "Barking Dogs food for dogs",
    price: 349,
    src: "../../img/foodservicesLandingPage/dogFood2.jpg",
  },
  {
    productType: "food",
    petType: "fish",
    name: "Tetra Min flakes for fish",
    price: 349,
    src: "../../img/foodservicesLandingPage/fishFood2.jpg",
  },
  {
    productType: "food",
    petType: "cat",
    name: "IAMS food for cats",
    price: 349,
    src: "../../img/foodservicesLandingPage/catFood2.jpg",
  },
  {
    productType: "food",
    petType: "bird",
    name: "Wagner's food for birds",
    price: 349,
    src: "../../img/foodservicesLandingPage/birdFood2.jpg",
  },
  {
    productType: "food",
    petType: "dog",
    name: "Crunch Bites for dogs",
    price: 349,
    src: "../../img/foodservicesLandingPage/dogFood3.jpg",
  },
  {
    productType: "food",
    petType: "fish",
    name: "Discus food mix for fish",
    price: 449,
    src: "../../img/foodservicesLandingPage/fishFood3.jpg",
  },
  {
    productType: "food",
    petType: "cat",
    name: "Perfect Bistro for cats",
    price: 349,
    src: "../../img/foodservicesLandingPage/catFood3.jpg",
  },
  {
    productType: "food",
    petType: "bird",
    name: "Wild Harvest for parrots",
    price: 349,
    src: "../../img/foodservicesLandingPage/birdFood3.jpg",
  },
  {
    productType: "food",
    petType: "dog",
    name: "IAMS food for dogs",
    price: 349,
    src: "../../img/foodservicesLandingPage/dogFood4.jpg",
  },
  {
    productType: "food",
    petType: "fish",
    name: "Discovery food for fish",
    price: 349,
    src: "../../img/foodservicesLandingPage/fishFood4.jpg",
  },
  {
    productType: "food",
    petType: "cat",
    name: "Kit Cat food for cat",
    price: 649,
    src: "../../img/foodservicesLandingPage/catFood4.jpg",
  },
  {
    productType: "food",
    petType: "bird",
    name: "Meal Worms for birds",
    price: 549,
    src: "../../img/foodservicesLandingPage/birdFood4.jpg",
  },
  {
    productType: "food",
    petType: "dog",
    name: "Wild Earth food for dogs",
    price: 449,
    src: "../../img/foodservicesLandingPage/dogFood5.jpg",
  },
  {
    productType: "food",
    petType: "cat",
    name: "Top Cat food for cats",
    price: 399,
    src: "../../img/foodservicesLandingPage/catFood5.jpg",
  },
  {
    productType: "food",
    petType: "fish",
    name: "Dried worms for fishes",
    price: 549,
    src: "../../img/foodservicesLandingPage/fishFood6.jpg",
  },
  {
    productType: "food",
    petType: "bird",
    name: "Peckish food for birds",
    price: 599,
    src: "../../img/foodservicesLandingPage/birdFood6.jpg",
  },
];
const dogData = [
  {
    productType: "pet",
    petType: "dog",
    name: "Affenpinscher",
    breed_group: "Toy",
    life_span: "10 - 12 years",
    src: "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg",
    rating: "4",
    price: 300,
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Afghan Hound",
    breed_group: "Hound",
    life_span: "10 - 13 years",
    price: 150,
    src: "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
    rating: "2",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "African Hunting Dog",
    life_span: "11 years",
    breed_group: "None",
    price: 200,
    src: "https://cdn2.thedogapi.com/images/rkiByec47.jpg",
    rating: "2",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Airedale Terrier",
    breed_group: "Terrier",
    life_span: "10 - 13 years",
    price: 250,
    src: "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
    rating: "2",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Akbash Dog",
    breed_group: "Working",
    life_span: "10 - 12 years",
    price: 225,
    src: "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
    rating: "2",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Akita",
    breed_group: "Working",
    life_span: "10 - 14 years",
    price: 5000,
    src: "https://cdn2.thedogapi.com/images/BFRYBufpm.jpg",
    rating: "5",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Alapaha Blue Blood Bulldog",
    breed_group: "Mixed",
    life_span: "12 - 13 years",
    price: 4000,
    src: "https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg",
    rating: "5",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Alaskan Husky",
    breed_group: "Mixed",
    life_span: "10 - 13 years",
    price: 3000,
    src: "https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg",
    rating: "5",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Alaskan Malamute",
    breed_group: "Working",
    life_span: "12 - 15 years",
    price: 3205,
    src: "https://cdn2.thedogapi.com/images/dW5UucTIW.jpg",
    rating: "5",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "American Bulldog",
    breed_group: "Working",
    life_span: "10 - 12 years",
    price: 5050,
    src: "https://cdn2.thedogapi.com/images/pk1AAdloG.jpg",
    rating: "1",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "American Bully",
    breed_group: "Working",
    life_span: "8 - 15 years",
    price: 125,
    src: "https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg",
    rating: "1",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "American Eskimo Dog",
    breed_group: "Non-Sporting",
    life_span: "12 - 15 years",
    price: 1000,
    src: "https://cdn2.thedogapi.com/images/Bymjyec4m.jpg",
    rating: "1",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "American Eskimo Dog (Miniature)",
    breed_group: "None",
    life_span: "13 -  15 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
    rating: "1",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "American Foxhound",
    breed_group: "Hound",
    life_span: "8 - 15 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/S14n1x9NQ.jpg",
    rating: "2",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "American Pit Bull Terrier",
    breed_group: "Terrier",
    life_span: "10 - 15 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/HkC31gcNm.jpg",
    rating: "2",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "American Staffordshire Terrier",
    breed_group: "Terrier",
    life_span: "12 - 15 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/rJIakgc4m.jpg",
    rating: "4",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "American Water Spaniel",
    breed_group: "Sporting",
    life_span: "10 - 12 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/SkmRJl9VQ.jpg",
    rating: "4",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Anatolian Shepherd Dog",
    breed_group: "Working",
    life_span: "11 - 13 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/BJT0Jx5Nm.jpg",
    rating: "4",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Appenzeller Sennenhund",
    breed_group: "None",
    life_span: "12 - 14 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/HkNkxlqEX.jpg",
    rating: "1",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Australian Cattle Dog",
    breed_group: "Herding",
    life_span: "12 - 14 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg",
    rating: "1",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Australian Kelpie",
    breed_group: "Herding",
    life_span: "10 - 13 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/Hyq1ge9VQ.jpg",
    rating: "1",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Australian Shepherd",
    breed_group: "Herding",
    life_span: "12 - 16 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/B1-llgq4m.jpg",
    rating: "1",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Australian Terrier",
    breed_group: "Terrier",
    life_span: "15 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/r1Ylge5Vm.jpg",
    rating: "5",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Azawakh",
    breed_group: "Hound",
    life_span: "10 - 13 years",
    price: 100,
    src: "https://cdn2.thedogapi.com/images/SkvZgx94m.jpg",
    rating: "5",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Barbet",
    breed_group: "None",
    life_span: "13 - 15 years",
    src: "https://cdn2.thedogapi.com/images/HyWGexcVQ.jpg",
    rating: "5",
    price: 5000,
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Basenji",
    breed_group: "Hound",
    life_span: "10 - 12 years",
    price: 5100,
    src: "https://cdn2.thedogapi.com/images/H1dGlxqNQ.jpg",
    rating: "5",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Basset Bleu de Gascogne",
    breed_group: "Hound",
    life_span: "10 - 14 years",
    price: 7000,
    src: "https://cdn2.thedogapi.com/images/BkMQll94X.jpg",
    rating: "3",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Basset Hound",
    breed_group: "Hound",
    life_span: "12 - 15 years",
    price: 5000,
    src: "https://cdn2.thedogapi.com/images/Sy57xx9EX.jpg",
    rating: "3",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Beagle",
    breed_group: "Hound",
    life_span: "13 - 16 years",
    price: 8000,
    src: "https://cdn2.thedogapi.com/images/Syd4xxqEm.jpg",
    rating: "3",
  },
  {
    productType: "pet",
    petType: "dog",
    name: "Bearded Collie",
    breed_group: "Herding",
    life_span: "12 - 14 years",
    price: 10000,
    src: "https://cdn2.thedogapi.com/images/A09F4c1qP.jpg",
    rating: "2",
  },
];
const catData = [
  {
    productType: "pet",
    petType: "cat",
    name: "Abyssinian",
    breed_group: "Guarding",
    life_span: "14 - 15",
    src: "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg",
    price: 1000,
    rating: 4,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Aegean",
    breed_group: "Hunting",
    life_span: "11-12",
    src: "https://cdn2.thecatapi.com/images/ozEvzdVM-.jpg",
    price: 2000,
    rating: 3,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "American Bobtail",
    breed_group: "Not Specifc",
    life_span: "11 - 15",
    src: "https://cdn2.thecatapi.com/images/hBXicehMA.jpg",
    price: 1000,
    rating: 1,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "American Curl",
    life_span: "11 - 15",
    breed_group: "Guarding",
    src: "https://cdn2.thecatapi.com/images/xnsqonbjW.jpg",
    price: 1000,
    rating: 2,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "American Shorthair",
    breed_group: "Hunting",
    life_span: "15 - 17",
    src: "https://cdn2.thecatapi.com/images/JFPROfGtQ.jpg",
    price: 1000,
    rating: 4,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Arabian Mau",
    life_span: "12-13",
    src: "https://cdn2.thecatapi.com/images/k71ULYfRr.jpg",
    price: 3000,
    rating: 3,
    breed_group: "Hunting",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Balinese",
    life_span: "10 - 15",
    src: "https://cdn2.thecatapi.com/images/13MkvUreZ.jpg",
    price: 3000,
    rating: 5,
    breed_group: "Guarding",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Bambino",
    src: "https://cdn2.thecatapi.com/images/5AdhMjeEu.jpg",
    price: 3000,
    rating: 1,
    breed_group: "Working",
    life_span: "11 - 13",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Birman",
    life_span: "14 - 15",
    src: "https://cdn2.thecatapi.com/images/HOrX5gwLS.jpg",
    price: 3000,
    rating: 4,
    breed_group: "Hunting",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Bombay",
    life_span: "12 - 16",
    src: "https://cdn2.thecatapi.com/images/5iYq9NmT1.jpg",
    price: 3000,
    breed_group: "Guarding",
    rating: 5,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "British Longhair",
    life_span: "12 - 14",
    src: "https://cdn2.thecatapi.com/images/7isAO4Cav.jpg",
    price: 3000,
    breed_group: "Working",
    rating: 3,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Burmese",
    breed_group: "Hunting",
    src: "https://cdn2.thecatapi.com/images/4lXnnfxac.jpg",
    price: 3000,
    rating: 2,
    life_span: "8 - 12",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Burmilla",
    life_span: "10 - 15",
    breed_group: "Guarding",
    src: "https://cdn2.thecatapi.com/images/jvg3XfEdC.jpg",
    price: 3000,
    rating: 1,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "California Spangled",
    life_span: "10 - 14",
    src: "https://cdn2.thecatapi.com/images/B1ERTmgph.jpg",
    price: 3000,
    rating: 4,
    breed_group: "Working",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Chartreux",
    life_span: "12 - 15",
    src: "https://cdn2.thecatapi.com/images/j6oFGLpRG.jpg",
    price: 4000,
    breed_group: "Working",
    rating: 5,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Chausie",
    life_span: "12 - 14",
    src: "https://cdn2.thecatapi.com/images/vJ3lEYgXr.jpg",
    price: 4000,
    rating: 3,
    breed_group: "Guarding",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Cheetoh",
    life_span: "12 - 14",
    src: "https://cdn2.thecatapi.com/images/IFXsxmXLm.jpg",
    price: 4000,
    rating: 1,
    breed_group: "Working",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Colorpoint Shorthair",
    src: "https://cdn2.thecatapi.com/images/oSpqGyUDS.jpg",
    price: 4000,
    rating: 4,
    breed_group: "Hunting",
    life_span: "6 - 8",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Cornish Rex",
    src: "https://cdn2.thecatapi.com/images/unX21IBVB.jpg",
    price: 4000,
    rating: 2,
    breed_group: "Guarding",
    life_span: "12 - 15",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Cymric",
    breed_group: "Guarding",
    life_span: "8 - 14",
    src: "https://cdn2.thecatapi.com/images/3dbtapCWM.jpg",
    price: 4000,
    rating: 5,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Cyprus",
    life_span: "12 - 15",
    src: "https://cdn2.thecatapi.com/images/tJbzb7FKo.jpg",
    price: 4000,
    rating: 1,
    breed_group: "Hunting",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Donskoy",
    life_span: "12 - 15",
    src: "https://cdn2.thecatapi.com/images/3KG57GfMW.jpg",
    price: 4000,
    rating: 2,
    breed_group: "Guarding",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Dragon Li",
    src: "https://cdn2.thecatapi.com/images/BQMSld0A0.jpg",
    price: 6000,
    life_span: "12 - 15",
    rating: 4,
    breed_group: "Guarding",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Egyptian Mau",
    breed_group: "Guarding",
    life_span: "18 - 20",
    src: "https://cdn2.thecatapi.com/images/TuSyTkt2n.jpg",
    price: 6000,
    rating: 1,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Exotic Shorthair",
    life_span: "12 - 15",
    src: "https://cdn2.thecatapi.com/images/YnPrYEmfe.jpg",
    price: 6000,
    rating: 1,
    breed_group: "Guarding",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Havana Brown",
    life_span: "10 - 15",
    src: "https://cdn2.thecatapi.com/images/njK25knLH.jpg",
    price: 6000,
    rating: 5,
    breed_group: "Hunting",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Himalayan",
    src: "https://cdn2.thecatapi.com/images/CDhOtM-Ig.jpg",
    price: 6000,
    rating: 2,
    life_span: "12 - 15",
    breed_group: "Guarding",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Japanese Bobtail",
    life_span: "14 - 16",
    src: "-tm9-https://cdn2.thecatapi.com/images/znzprice:8000l.jpg",
    price: 4000,
    life_span: "12 - 15",
    breed_group: "Working",
    rating: 4,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Javanese",
    life_span: "10 - 12",
    src: "https://cdn2.thecatapi.com/images/xoI_EpOKe.jpg",
    price: 8000,
    rating: 3,
    life_span: "12 - 15",
    breed_group: "Hunting",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Khao Manee",
    src: "https://cdn2.thecatapi.com/images/165ok6ESN.jpg",
    price: 8000,
    rating: 5,
    breed_group: "Working",
    life_span: "12 - 15",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Kurilian",
    src: "https://cdn2.thecatapi.com/images/NZpO4pU56M.jpg",
    price: 8000,
    life_span: "12 - 15",
    breed_group: "Hunting",
    rating: 3,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "LaPerm",
    src: "https://cdn2.thecatapi.com/images/aKbsEYjSl.jpg",
    price: 8000,
    rating: 3,
    life_span: "12 - 15",
    breed_group: "Hunting",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Maine Coon",
    breed_group: "Hunting",
    life_span: "12 - 15",
    src: "https://cdn2.thecatapi.com/images/OOD3VXAQn.jpg",
    price: 4500,
    rating: 3,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Manx",
    breed_group: "Guarding",
    life_span: "12 - 14",
    src: "https://cdn2.thecatapi.com/images/fhYh2PDcC.jpg",
    price: 4500,
    rating: 3,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Munchkin",
    life_span: "10 - 15",
    src: "https://cdn2.thecatapi.com/images/j5cVSqLer.jpg",
    price: 4500,
    rating: 3,
    breed_group: "Guarding",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Nebelung",
    life_span: "11 - 16",
    src: "https://cdn2.thecatapi.com/images/OGTWqNNOt.jpg",
    price: 4500,
    rating: 4,
    breed_group: "Guarding",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Norwegian Forest Cat",
    life_span: "12 - 16",
    src: "https://cdn2.thecatapi.com/images/06dgGmEOV.jpg",
    price: 4500,
    breed_group: "Working",
    rating: 4,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Oriental",
    life_span: "12 - 14",
    src: "https://cdn2.thecatapi.com/images/LutjkZJpH.jpg",
    price: 4500,
    rating: 4,
    breed_group: "Hunting",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Persian",
    breed_group: "Hunting",
    life_span: "14 - 15",
    src: "-https://cdn2.thecatapi.com/images/Zfz5z2jK.jpg",
    price: 4500,
    rating: 4,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Pixie-bob",
    life_span: "13 - 16",
    src: "https://cdn2.thecatapi.com/images/z7fJRNeN6.jpg",
    price: 4500,
    rating: 4,
    breed_group: "Hunting",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Savannah",
    life_span: "17 - 20",
    src: "https://cdn2.thecatapi.com/images/a8nIYvs6S.jpg",
    price: 4500,
    rating: 4,
    breed_group: "Working",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Scottish Fold",
    life_span: "11 - 14",
    src: "https://cdn2.thecatapi.com/images/o9t0LDcsa.jpg",
    price: 4500,
    breed_group: "Working",
    rating: 4,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Selkirk Rex",
    src: "https://cdn2.thecatapi.com/images/II9dOZmrw.jpg",
    price: 6000,
    rating: 5,
    life_span: "12-14",
    breed_group: "Hunting",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Siamese",
    life_span: "12 - 15",
    src: "https://cdn2.thecatapi.com/images/ai6Jps4sx.jpg",
    price: 4500,
    breed_group: "Hunting",
    rating: 5,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Siberian",
    breed_group: "Hunting",
    src: "https://cdn2.thecatapi.com/images/3bkZAjRh1.jpg",
    price: 4500,
    rating: 3,
    life_span: "11 - 14",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Singapura",
    life_span: "12 - 15",
    breed_group: "Hunting",
    src: "https://cdn2.thecatapi.com/images/Qtncp2nRe.jpg",
    price: 4500,
    rating: 2,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Somali",
    life_span: "12 - 16",
    src: "https://cdn2.thecatapi.com/images/EPF2ejNS0.jpg",
    price: 4000,
    breed_group: "Hunting",
    rating: 5,
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Sphynx",
    life_span: "12 - 14",
    src: "https://cdn2.thecatapi.com/images/BDb8ZXb1v.jpg",
    price: 500,
    rating: 2,
    breed_group: "Hunting",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Tonkinese",
    src: "https://cdn2.thecatapi.com/images/KBroiVNCM.jpg",
    price: 1500,
    rating: 3,
    life_span: "12 - 14",
    breed_group: "Working",
  },
  {
    productType: "pet",
    petType: "cat",
    name: "Toyger",
    life_span: "12 - 15",
    src: "https://cdn2.thecatapi.com/images/O3F3_S1XN.jpg",
    price: 500,
    rating: 2,
    breed_group: "Hunting",
  },
];

router.get("/", (request, response) => {
  return response.status(234).send("Welcome To MERN Stack Tutorial");
});

export default router;
