name: Node.JS CI/CD

on:
  push:
    paths:
    - 'server/**'
    branches: ["master"]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.JS ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies and run tests
      env:
        MONGO_URL: ${{ secrets.pets.MONGO_URL }}
        PORT: ${{ secrets.pets.PORT }}
        JWT_SECRET: ${{ secrets.pets.JWT_SECRET }}
        OTP_LENGTH: ${{ secrets.pets.OTP_LENGTH }}
        MAIL_HOST: ${{ secrets.pets.MAIL_HOST }}
        MAIL_USER: ${{ secrets.pets.MAIL_USER }}
        MAIL_PASS: ${{ secrets.pets.MAIL_PASS }}
        REDIS_PWD: ${{ secrets.pets.REDIS_PWD }}
        REDIS_HOST: ${{ secrets.pets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.pets.REDIS_PORT }}
      run: |
        npm install
        npm start
        npm test
      
      working-directory: server
